//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Msg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Msg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Msg", typeof(Msg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao carregar o funcionário..
        /// </summary>
        internal static string Erro_carregar_funcionario {
            get {
                return ResourceManager.GetString("Erro_carregar_funcionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao criar o funcionário..
        /// </summary>
        internal static string Erro_criar_funcionario_partir_comando {
            get {
                return ResourceManager.GetString("Erro_criar_funcionario_partir_comando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O NIF indicado já foi atribuído a outro funcionário..
        /// </summary>
        internal static string Nif_duplicado {
            get {
                return ResourceManager.GetString("Nif_duplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este registo já foi modificado por outro utilizador..
        /// </summary>
        internal static string Objeto_modificado_por_outro_utilizador {
            get {
                return ResourceManager.GetString("Objeto_modificado_por_outro_utilizador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A string não pode ser vazia..
        /// </summary>
        internal static string String_vazia {
            get {
                return ResourceManager.GetString("String_vazia", resourceCulture);
            }
        }
    }
}
